name: PaperPersistence
version: 2.1.0
main: com.floogoobooq.blackomega.paperpersistence.PaperPersistence
api-version: 1.18
commands:
  makepersistent:
    description: Uses a Reinforced Emerald to make an item Persistent.
    usage: "Usage: /<command> <player> <main | offhand>"