name: PaperPersistence
version: 1.0
main: com.floogoobooq.blackomega.paperpersistence.PaperPersistence
api-version: 1.15
commands:
  makepersistent:
    description: Uses a Reinforced Emerald to make an item Persistent.
    usage: /makepersistent <player>